### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by karan** [peterhellberg/fuzz#1]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by peterhellberg** [comment]
That is OK since this isn’t meant to be a (stand alone) open source project to begin with.

Both of these projects are licensed under MIT:
- https://github.com/peterhellberg/duration
- https://github.com/peterhellberg/link
